---
- name: Add Nginx PPA
  apt_repository: repo="ppa:rtcamp/nginx" update_cache=yes

- name: Install Nginx
  apt: name=nginx state=present force=yes

- name: Create nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Disable Nginx from starting on boot
  service: name=nginx enabled=no state=stopped

- name: Disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Create PHP-FPM WordPress site configuration
  template: src=wp-php-fpm.conf.j2
            dest=/etc/nginx/sites-available/wp-php-fpm.conf

- name: Enable PHP-FPM WordPress site configuration
  file: src="/etc/nginx/sites-available/wp-php-fpm.conf"
        dest="/etc/nginx/sites-enabled/wp-php-fpm.conf"
        owner=root
        group=root
        state=link
  notify: start nginx
  when: wp_php_fpm is defined

- name: Create HHVM WordPress site configuration
  template: src=wp-hhvm.conf.j2
            dest=/etc/nginx/sites-available/wp-hhvm.conf

- name: Enable HHVM WordPress site configuration
  file: src="/etc/nginx/sites-available/wp-hhvm.conf"
        dest="/etc/nginx/sites-enabled/wp-hhvm.conf"
        owner=root
        group=root
        state=link
  notify: start nginx
  when: wp_hhvm is defined