---
- name: Create WordPress database
  mysql_db: name="{{ wordpress_db_name }}"
            state=present
            login_user=root
            login_password="{{ mysql_root_password }}"

- name: Create WordPress DB user and grant permissions to WordPress DB
  mysql_user: name="{{ wordpress_db_user }}"
              password="{{ wordpress_db_user_pass }}"
              priv="{{ wordpress_db_name }}.*:ALL"
              state=present
              login_user="root"
              login_password="{{ mysql_root_password }}"

- name: Is WordPress downloaded?
  stat: path="{{ remote_wordpress_dir }}/index.php"
  register: wp_dir

- name: Create WordPress directory
  file: path="{{ remote_wordpress_dir }}"
        owner="{{ remote_deploy_user }}"
        group="{{ remote_deploy_group }}"
        mode=0755
        state=directory
  when: wp_dir.stat.isdir is not defined

- name: Download WordPress
  command: wp core download
  args:
      chdir: "{{ remote_wordpress_dir }}/"
  remote_user: "{{ remote_deploy_user }}"
  when: wp_dir.stat.isdir is not defined

- name: Configure WordPress
  command: wp core config
           --path="{{ remote_wordpress_dir }}"
           --dbname="{{ wordpress_db_name }}"
           --dbuser="{{ wordpress_db_user }}"
           --dbpass="{{ wordpress_db_user_pass }}"
           --dbprefix="{{ wordpress_db_prefix }}"
  remote_user: "{{ remote_deploy_user }}"
  when: wp_dir.stat.isdir is not defined

- name: Is WordPress installed?
  command: wp core is-installed
  args:
    chdir: "{{ remote_wordpress_dir }}/"
  register: wordpress_is_installed
  ignore_errors: True
  remote_user: "{{ remote_deploy_user }}"

- name: Install WordPress tables
  command: wp core install
            --url="{{ wordpress_home_url }}"
            --title="{{ wordpress_site_title }}"
            --admin_user="{{ wordpress_admin_user }}"
            --admin_password="{{ wordpress_admin_user_pass }}"
            --admin_email="{{ wordpress_admin_email }}"
  args:
      chdir: "{{ remote_wordpress_dir }}/"
  when: wordpress_is_installed|failed
  remote_user: "{{ remote_deploy_user }}"

- name: Install WordPress theme
  command: "wp theme install {{ wordpress_theme }} --activate"
  args:
    chdir: "{{ remote_wordpress_dir }}"
  when: wp_advanced is defined

- name: Install WordPress plugins
  command: "wp plugin install {{ item }} --activate"
  args:
    chdir: "{{ remote_wordpress_dir }}"
  with_items: wordpress_plugins
  when: wp_advanced is defined

- name: Download WordPress dummy data
  get_url:
    url: https://raw.githubusercontent.com/manovotny/wptest/master/wptest.xml
    dest: "{{ remote_wordpress_dir }}/wptest.xml"
  when: wp_advanced is defined

- name: Import WordPress dummy data
  command: "wp import {{ item }} --authors=create"
  args:
    chdir: "{{ remote_wordpress_dir }}"
  with_items:
  - wp-content/plugins/woocommerce/dummy-data/dummy-data.xml
  - wptest.xml
  when: wp_dummy_data is defined
